spring.application.name=tmanager
#JPA y H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update
spring.h2.console.enabled = true
spring.h2.console.path = /h2-ui

#JWT
jwt.secret=8e182f4fee0d48218d6f485a7e81bd9ba03d6b1f03efb3196660250db0902b3b
#1 hora en ms
jwt.expiration=3600000  

#OpenAPI
springdoc.api-docs.enabled=true
springdoc.api-docs.format=yaml
springdoc.api-docs.path=/v3/api-docs
springdoc.output.file.enabled=true
springdoc.output.file.location=target/openapi.yaml

#Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
